org.gradle.jvmargs=-Xmx6g -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8 -XX:+UseParallelGC -XX:MaxMetaspaceSize=1g
kotlin.code.style=official
android.useAndroidX=true
android.debug.obsoleteApi=true
android.nonTransitiveRClass=true
android.experimental.testOptions.managedDevices.allowOldApiLevelDevices=true
android.experimental.enableScreenshotTest=true
#org.gradle.java.home=D:/Download/tools/WebStorm/WebStorm 2024.1.5/jbr
