@file:JvmName("FocusModeCallbacks")

package li.songe.gkd.sdp.ui

import li.songe.gkd.sdp.data.FocusRule

data class FocusModeCallbacks(
    val onBack: () -> Unit,
    val onOpenRuleEditor: () -> Unit,
    val onEditRule: (FocusRule) -> Unit,
    val onDismissRuleEditor: () -> Unit,
    val onSaveRule: () -> Unit,
    val onRuleNameChange: (String) -> Unit,
    val onRuleTypeChange: (Int) -> Unit,
    val onRuleStartTimeChange: (String) -> Unit,
    val onRuleEndTimeChange: (String) -> Unit,
    val onRuleDaysOfWeekChange: (List<Int>) -> Unit,
    val onRuleDurationHoursChange: (Int) -> Unit,
    val onRuleDurationMinutesChange: (Int) -> Unit,
    val onRuleWhitelistChange: (List<String>) -> Unit,
    val onRuleInterceptMessageChange: (String) -> Unit,
    val onRuleIsLockedChange: (Boolean) -> Unit,
    val onRuleLockDurationChange: (Int) -> Unit,
    val onOpenQuickStart: () -> Unit,
    val onDismissQuickStart: () -> Unit,
    val onStartManualSession: () -> Unit,
    val onManualHoursChange: (Int) -> Unit,
    val onManualMinutesChange: (Int) -> Unit,
    val onManualMessageChange: (String) -> Unit,
    val onManualWhitelistChange: (List<String>) -> Unit,
    val onManualIsLockedChange: (Boolean) -> Unit,
    val onManualLockDurationChange: (Int) -> Unit,
    val onToggleRuleEnabled: (FocusRule) -> Unit,
    val onDeleteRule: (FocusRule) -> Unit,
    val onStartQuickRule: (FocusRule) -> Unit,
    val onStopManualSession: () -> Unit,
    val onRemoveFromSessionWhitelist: (String) -> Unit,
    val onOpenRuleWhitelistPicker: () -> Unit,
    val onOpenManualWhitelistPicker: () -> Unit,
    val onDismissWhitelistPicker: () -> Unit,
    val onWhitelistConfirm: (List<String>) -> Unit,
    val onWhitelistSearchQueryChange: (String) -> Unit,
    val onClearWhitelistSearchQuery: () -> Unit,
    val onShowSystemAppsInWhitelistChange: (Boolean) -> Unit,
    val onOpenRuleLock: (FocusRule) -> Unit,
    val onDismissRuleLock: () -> Unit,
    val onLockRuleTarget: () -> Unit,
    val onSelectedLockDurationChange: (Int) -> Unit,
    val onCustomLockDurationChange: (Boolean) -> Unit,
    val onCustomLockDaysTextChange: (String) -> Unit,
    val onCustomLockHoursTextChange: (String) -> Unit,
)
